"""make cart public_id unique

Revision ID: 02115aa57297
Revises: 22e97ccfbeab
Create Date: 2023-12-24 16:56:30.389130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02115aa57297'
down_revision = '22e97ccfbeab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.drop_index('ix_cart_public_id')
        batch_op.create_index(batch_op.f('ix_cart_public_id'), ['public_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cart_public_id'))
        batch_op.create_index('ix_cart_public_id', ['public_id'], unique=False)

    # ### end Alembic commands ###
