"""add cartitem table and relationships

Revision ID: 22e97ccfbeab
Revises: 03c4480f1e98
Create Date: 2023-12-22 12:22:30.239463

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '22e97ccfbeab'
down_revision = '03c4480f1e98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cart_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('product_id', sa.String(length=60), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['cart.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total', sa.Float(), nullable=False))
        batch_op.alter_column('public_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=60),
               nullable=False)
        batch_op.drop_index('ix_cart_public_id')
        batch_op.create_index(batch_op.f('ix_cart_public_id'), ['public_id'], unique=False)
        batch_op.drop_column('contents')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contents', sqlite.JSON(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_cart_public_id'))
        batch_op.create_index('ix_cart_public_id', ['public_id'], unique=1)
        batch_op.alter_column('public_id',
               existing_type=sa.String(length=60),
               type_=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('total')

    op.drop_table('cart_item')
    # ### end Alembic commands ###
